name: Sync with Hugging Face

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-with-huggingface.yml
      - app/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: ${{ runner.os }}-cache-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-cache-

    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.5
      with:
        github_repo_id: 'myscale/ChatData'
        huggingface_repo_id: 'myscale/ChatData'
        hf_token: ${{ secrets.HF_TOKEN }}
        repo_type: 'space'
        private: false
        space_sdk: 'streamlit'
        subdirectory: app
